name: sonarqube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Login to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_REPO }}
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_REPO }}" --password-stdin

      - name: SonarQube Scan (back-end)
        #uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd back
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=BobApp \
          -Dsonar.projectName='BobApp'

      - name: Clean SonarQube Cache
        run: rm -rf /home/runner/.sonar/_tmp/

      - name: SonarQube Scan (front-end)
        #uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd front
          npm install
          npx sonar-scanner \
          -Dsonar.projectKey=BobApp \
          -Dsonar.sources=src/app \
          -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info \
          -Dsonar.token=${{ secrets.SONAR_TOKEN_FRONT }} \
          -Dsonar.ws.timeout=36000 \
          -Dsonar.plugins.javascript.version=10.15.0.27423 \
          -Dsonar.exclusions=**/*.spec.ts,**/*.test.js,node_modules/**,src/assets/**,src/polyfills.ts,src/index.html,src/environments/*
      

      - name: Build Docker images
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_REPO }}/sonarqube-bobapp-back:latest .
            
          cd ../front
          docker build -t ${{ secrets.DOCKER_REPO }}/sonarqube-bobapp-front:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/sonarqube-bobapp-back:latest
          docker push ${{ secrets.DOCKER_REPO }}/sonarqube-bobapp-front:latest